// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Body$App = require("../components/Body.bs.js");
var Formality = require("re-formality/src/Formality.bs.js");
var Config$App = require("../Config.bs.js");
var Footer$App = require("../components/Footer.bs.js");
var Header$App = require("../components/Header.bs.js");
var String$App = require("../components/String.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Validator$App = require("../Validator.bs.js");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js");
var MaterialUi_FormGroup = require("@jsiebern/bs-material-ui/src/MaterialUi_FormGroup.bs.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");
var MaterialUi_FormControl = require("@jsiebern/bs-material-ui/src/MaterialUi_FormControl.bs.js");
var Formality__PublicHelpers = require("re-formality/src/Formality__PublicHelpers.bs.js");
var Formality__FormAsyncOnChange = require("re-formality/src/Formality__FormAsyncOnChange.bs.js");

var debounceInterval = Formality.Async[/* debounceInterval */2];

function update(state, value) {
  return /* record */[
          /* email */value,
          /* password */state[/* password */1]
        ];
}

function validator_003(param) {
  return Validator$App.FInterop[/* use */0](/* Email */0, param[/* email */0]);
}

var validator = /* record */[
  /* field : Email */0,
  /* strategy : OnFirstSuccessOrFirstBlur */3,
  /* dependents */undefined,
  validator_003,
  /* validateAsync */undefined
];

var EmailField = /* module */[
  /* update */update,
  /* validator */validator
];

function update$1(state, value) {
  return /* record */[
          /* email */state[/* email */0],
          /* password */value
        ];
}

function validator_003$1(param) {
  return Validator$App.FInterop[/* use */0](/* Password */1, param[/* password */1]);
}

var validator$1 = /* record */[
  /* field : Password */1,
  /* strategy : OnFirstSuccessOrFirstBlur */3,
  /* dependents */undefined,
  validator_003$1,
  /* validateAsync */undefined
];

var PasswordField = /* module */[
  /* update */update$1,
  /* validator */validator$1
];

var validators_001 = /* :: */[
  validator$1,
  /* [] */0
];

var validators = /* :: */[
  validator,
  validators_001
];

var Form = /* module */[
  /* debounceInterval */debounceInterval,
  /* EmailField */EmailField,
  /* PasswordField */PasswordField,
  /* validators */validators
];

var controls = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.justifyContent(Css.spaceBetween),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* controls */controls];

var AsyncFormContainer = Formality__FormAsyncOnChange.Make([
      debounceInterval,
      validators
    ]);

var initialState = /* record */[
  /* email */"",
  /* password */""
];

function renderEmailField(form) {
  var match = Curry._1(form[/* result */2], /* Email */0);
  var tmp;
  if (match !== undefined) {
    var match$1 = match;
    tmp = match$1.tag ? true : false;
  } else {
    tmp = false;
  }
  var match$2 = Curry._1(form[/* result */2], /* Email */0);
  var tmp$1;
  if (match$2 !== undefined) {
    var match$3 = match$2;
    tmp$1 = match$3.tag ? ReasonReact.element(undefined, undefined, String$App.make(match$3[0], /* array */[])) : ReasonReact.element(undefined, undefined, String$App.make("Email", /* array */[]));
  } else {
    tmp$1 = ReasonReact.element(undefined, undefined, String$App.make("Email", /* array */[]));
  }
  return ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, undefined, undefined, form[/* submitting */5], tmp, undefined, undefined, undefined, "email", undefined, undefined, undefined, undefined, Caml_option.some(tmp$1), /* Normal */-453122489, undefined, undefined, (function (param) {
                              return Curry._1(form[/* blur */7], /* Email */0);
                            }), (function ($$event) {
                              return Curry._2(form[/* change */6], /* Email */0, update(form[/* state */0], $$event.target.value));
                            }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `String */[
                            -976970511,
                            form[/* state */0][/* email */0]
                          ], undefined, undefined, /* array */[]))]));
}

function renderPasswordField(form) {
  var match = Curry._1(form[/* result */2], /* Password */1);
  var tmp;
  if (match !== undefined) {
    var match$1 = match;
    tmp = match$1.tag ? true : false;
  } else {
    tmp = false;
  }
  var match$2 = Curry._1(form[/* result */2], /* Password */1);
  var tmp$1;
  if (match$2 !== undefined) {
    var match$3 = match$2;
    tmp$1 = match$3.tag ? ReasonReact.element(undefined, undefined, String$App.make(match$3[0], /* array */[])) : ReasonReact.element(undefined, undefined, String$App.make("Password", /* array */[]));
  } else {
    tmp$1 = ReasonReact.element(undefined, undefined, String$App.make("Password", /* array */[]));
  }
  return ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, undefined, undefined, form[/* submitting */5], tmp, undefined, undefined, undefined, "password", undefined, undefined, undefined, undefined, Caml_option.some(tmp$1), /* Normal */-453122489, undefined, undefined, (function (param) {
                              return Curry._1(form[/* blur */7], /* Password */1);
                            }), (function ($$event) {
                              return Curry._2(form[/* change */6], /* Password */1, update$1(form[/* state */0], $$event.target.value));
                            }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, "password", /* `String */[
                            -976970511,
                            form[/* state */0][/* password */1]
                          ], undefined, undefined, /* array */[]))]));
}

function renderSubmitButtons(form) {
  return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, /* Dense */-363472001, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, form[/* submitting */5], undefined, undefined, undefined, undefined, undefined, undefined, undefined, "submit", /* Contained */-515484397, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, String$App.make("Login", /* array */[]))]))])), ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, /* Dense */-363472001, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* Outlined */-28821822, undefined, undefined, undefined, undefined, undefined, undefined, (function (_event) {
                                  return ReasonReact.Router[/* push */0](Config$App.routes[/* register */2]);
                                }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, String$App.make("Register", /* array */[]))]))])));
}

function renderLoginForm(param) {
  return ReasonReact.element(undefined, undefined, Curry._3(AsyncFormContainer[/* make */4], initialState, (function (state, form) {
                    return /* () */0;
                  }), (function (form) {
                    var partial_arg = form[/* submit */8];
                    var partial_arg$1 = Formality__PublicHelpers.Dom[/* preventDefault */0];
                    return React.createElement("form", {
                                onSubmit: (function (param) {
                                    return partial_arg$1(partial_arg, param);
                                  })
                              }, ReasonReact.element(undefined, undefined, MaterialUi_FormGroup.make(undefined, undefined, undefined, undefined, /* array */[
                                        renderEmailField(form),
                                        renderPasswordField(form),
                                        renderSubmitButtons(form)
                                      ])));
                  })));
}

var component = ReasonReact.statelessComponent("Login-App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, Header$App.make(/* array */[])), ReasonReact.element(undefined, undefined, Body$App.make(/* array */[renderLoginForm(/* () */0)])), ReasonReact.element(undefined, undefined, Footer$App.make(/* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Form = Form;
exports.Styles = Styles;
exports.AsyncFormContainer = AsyncFormContainer;
exports.initialState = initialState;
exports.renderEmailField = renderEmailField;
exports.renderPasswordField = renderPasswordField;
exports.renderSubmitButtons = renderSubmitButtons;
exports.renderLoginForm = renderLoginForm;
exports.component = component;
exports.make = make;
/* controls Not a pure module */
