// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Body$App = require("../components/Body.bs.js");
var Formality = require("re-formality/src/Formality.bs.js");
var Footer$App = require("../components/Footer.bs.js");
var Header$App = require("../components/Header.bs.js");
var String$App = require("../components/String.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Validator$App = require("../Validator.bs.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js");
var Formality__PublicHelpers = require("re-formality/src/Formality__PublicHelpers.bs.js");
var Formality__FormAsyncOnChange = require("re-formality/src/Formality__FormAsyncOnChange.bs.js");

var debounceInterval = Formality.Async[/* debounceInterval */2];

function update(state, value) {
  return /* record */[
          /* email */value,
          /* password */state[/* password */1]
        ];
}

function validator_003(param) {
  return Validator$App.FInterop[/* use */0](/* Email */0, param[/* email */0]);
}

var validator = /* record */[
  /* field : Email */0,
  /* strategy : OnFirstSuccessOrFirstBlur */3,
  /* dependents */undefined,
  validator_003,
  /* validateAsync */undefined
];

var EmailField = /* module */[
  /* update */update,
  /* validator */validator
];

function update$1(state, value) {
  return /* record */[
          /* email */state[/* email */0],
          /* password */value
        ];
}

function validator_003$1(param) {
  return Validator$App.FInterop[/* use */0](/* Password */1, param[/* password */1]);
}

var validator$1 = /* record */[
  /* field : Password */1,
  /* strategy : OnFirstBlur */0,
  /* dependents */undefined,
  validator_003$1,
  /* validateAsync */undefined
];

var PasswordField = /* module */[
  /* update */update$1,
  /* validator */validator$1
];

var validators_001 = /* :: */[
  validator$1,
  /* [] */0
];

var validators = /* :: */[
  validator,
  validators_001
];

var Form = /* module */[
  /* debounceInterval */debounceInterval,
  /* EmailField */EmailField,
  /* PasswordField */PasswordField,
  /* validators */validators
];

var AsyncFormContainer = Formality__FormAsyncOnChange.Make([
      debounceInterval,
      validators
    ]);

function renderBody(param) {
  return ReasonReact.element(undefined, undefined, Body$App.make(/* array */[ReasonReact.element(undefined, undefined, Curry._3(AsyncFormContainer[/* make */4], /* record */[
                            /* email */"",
                            /* password */""
                          ], (function (state, form) {
                              return /* () */0;
                            }), (function (form) {
                              var partial_arg = form[/* submit */8];
                              var partial_arg$1 = Formality__PublicHelpers.Dom[/* preventDefault */0];
                              return React.createElement("form", {
                                          onSubmit: (function (param) {
                                              return partial_arg$1(partial_arg, param);
                                            })
                                        }, ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                                  ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, /* V12 */11, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* Contained */-515484397, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, String$App.make("Login", /* array */[]))]))])),
                                                  ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, /* V12 */11, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* Contained */-515484397, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, String$App.make("Register", /* array */[]))]))]))
                                                ])));
                            })))]));
}

var component = ReasonReact.statelessComponent("Login-App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, Header$App.make(/* array */[])), renderBody(/* () */0), ReasonReact.element(undefined, undefined, Footer$App.make(/* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Form = Form;
exports.AsyncFormContainer = AsyncFormContainer;
exports.renderBody = renderBody;
exports.component = component;
exports.make = make;
/* AsyncFormContainer Not a pure module */
