// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Body$App = require("../components/Body.bs.js");
var Formality = require("re-formality/src/Formality.bs.js");
var Config$App = require("../Config.bs.js");
var Footer$App = require("../components/Footer.bs.js");
var Header$App = require("../components/Header.bs.js");
var String$App = require("../components/String.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Validator$App = require("../Validator.bs.js");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js");
var MaterialUi_FormGroup = require("@jsiebern/bs-material-ui/src/MaterialUi_FormGroup.bs.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");
var MaterialUi_FormControl = require("@jsiebern/bs-material-ui/src/MaterialUi_FormControl.bs.js");
var Formality__PublicHelpers = require("re-formality/src/Formality__PublicHelpers.bs.js");
var Formality__FormAsyncOnChange = require("re-formality/src/Formality__FormAsyncOnChange.bs.js");

var debounceInterval = Formality.Async[/* debounceInterval */2];

function update(state, value) {
  return /* record */[
          /* email */value,
          /* firstName */state[/* firstName */1],
          /* lastName */state[/* lastName */2],
          /* password */state[/* password */3],
          /* passwordConfirmation */state[/* passwordConfirmation */4]
        ];
}

function validator_003(param) {
  return Validator$App.FInterop[/* use */0](/* Email */0, param[/* email */0]);
}

var validator = /* record */[
  /* field : Email */2,
  /* strategy : OnFirstSuccessOrFirstBlur */3,
  /* dependents */undefined,
  validator_003,
  /* validateAsync */undefined
];

var EmailField = /* module */[
  /* update */update,
  /* validator */validator
];

function update$1(state, value) {
  return /* record */[
          /* email */state[/* email */0],
          /* firstName */value,
          /* lastName */state[/* lastName */2],
          /* password */state[/* password */3],
          /* passwordConfirmation */state[/* passwordConfirmation */4]
        ];
}

function validator_003$1(param) {
  return Validator$App.FInterop[/* use */0](/* MinLength */Block.__(0, [3]), param[/* firstName */1]);
}

var validator$1 = /* record */[
  /* field : FirstName */0,
  /* strategy : OnFirstSuccessOrFirstBlur */3,
  /* dependents */undefined,
  validator_003$1,
  /* validateAsync */undefined
];

var FirstNameField = /* module */[
  /* update */update$1,
  /* validator */validator$1
];

function update$2(state, value) {
  return /* record */[
          /* email */state[/* email */0],
          /* firstName */state[/* firstName */1],
          /* lastName */value,
          /* password */state[/* password */3],
          /* passwordConfirmation */state[/* passwordConfirmation */4]
        ];
}

function validator_003$2(_state) {
  return /* Ok */Block.__(0, [/* Valid */0]);
}

var validator$2 = /* record */[
  /* field : LastName */1,
  /* strategy : OnFirstSuccessOrFirstBlur */3,
  /* dependents */undefined,
  validator_003$2,
  /* validateAsync */undefined
];

var LastNameField = /* module */[
  /* update */update$2,
  /* validator */validator$2
];

function update$3(state, value) {
  return /* record */[
          /* email */state[/* email */0],
          /* firstName */state[/* firstName */1],
          /* lastName */state[/* lastName */2],
          /* password */value,
          /* passwordConfirmation */state[/* passwordConfirmation */4]
        ];
}

function validator_003$3(param) {
  return Validator$App.FInterop[/* use */0](/* Password */1, param[/* password */3]);
}

var validator$3 = /* record */[
  /* field : Password */3,
  /* strategy : OnFirstSuccessOrFirstBlur */3,
  /* dependents */undefined,
  validator_003$3,
  /* validateAsync */undefined
];

var PasswordField = /* module */[
  /* update */update$3,
  /* validator */validator$3
];

function update$4(state, value) {
  return /* record */[
          /* email */state[/* email */0],
          /* firstName */state[/* firstName */1],
          /* lastName */state[/* lastName */2],
          /* password */state[/* password */3],
          /* passwordConfirmation */value
        ];
}

function validator_003$4(param) {
  var passwordConfirmation = param[/* passwordConfirmation */4];
  if (param[/* password */3] !== passwordConfirmation) {
    return /* Error */Block.__(1, ["Password doesn't match"]);
  } else if (passwordConfirmation === "") {
    return /* Error */Block.__(1, ["Password confirmation is required"]);
  } else {
    return /* Ok */Block.__(0, [/* Valid */0]);
  }
}

var validator$4 = /* record */[
  /* field : PasswordConfirmation */4,
  /* strategy : OnFirstSuccessOrFirstBlur */3,
  /* dependents */undefined,
  validator_003$4,
  /* validateAsync */undefined
];

var PasswordConfirmationField = /* module */[
  /* update */update$4,
  /* validator */validator$4
];

var validators_001 = /* :: */[
  validator$2,
  /* :: */[
    validator,
    /* :: */[
      validator$3,
      /* :: */[
        validator$4,
        /* [] */0
      ]
    ]
  ]
];

var validators = /* :: */[
  validator$1,
  validators_001
];

var Form = /* module */[
  /* debounceInterval */debounceInterval,
  /* EmailField */EmailField,
  /* FirstNameField */FirstNameField,
  /* LastNameField */LastNameField,
  /* PasswordField */PasswordField,
  /* PasswordConfirmationField */PasswordConfirmationField,
  /* validators */validators
];

var controls = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.justifyContent(Css.spaceBetween),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* controls */controls];

var initialState = /* record */[
  /* email */"",
  /* firstName */"",
  /* lastName */"",
  /* password */"",
  /* passwordConfirmation */""
];

var AsyncFormContainer = Formality__FormAsyncOnChange.Make([
      debounceInterval,
      validators
    ]);

function renderBody(param) {
  return ReasonReact.element(undefined, undefined, Body$App.make(/* array */[ReasonReact.element(undefined, undefined, Curry._3(AsyncFormContainer[/* make */4], initialState, (function (state, form) {
                              return /* () */0;
                            }), (function (form) {
                              var partial_arg = form[/* submit */8];
                              var partial_arg$1 = Formality__PublicHelpers.Dom[/* preventDefault */0];
                              var match = Curry._1(form[/* result */2], /* FirstName */0);
                              var tmp;
                              if (match !== undefined) {
                                var match$1 = match;
                                tmp = match$1.tag ? true : false;
                              } else {
                                tmp = false;
                              }
                              var match$2 = Curry._1(form[/* result */2], /* FirstName */0);
                              var tmp$1;
                              if (match$2 !== undefined) {
                                var match$3 = match$2;
                                tmp$1 = match$3.tag ? ReasonReact.element(undefined, undefined, String$App.make(match$3[0], /* array */[])) : ReasonReact.element(undefined, undefined, String$App.make("FirstName", /* array */[]));
                              } else {
                                tmp$1 = ReasonReact.element(undefined, undefined, String$App.make("FirstName", /* array */[]));
                              }
                              var match$4 = Curry._1(form[/* result */2], /* Email */2);
                              var tmp$2;
                              if (match$4 !== undefined) {
                                var match$5 = match$4;
                                tmp$2 = match$5.tag ? true : false;
                              } else {
                                tmp$2 = false;
                              }
                              var match$6 = Curry._1(form[/* result */2], /* Email */2);
                              var tmp$3;
                              if (match$6 !== undefined) {
                                var match$7 = match$6;
                                tmp$3 = match$7.tag ? ReasonReact.element(undefined, undefined, String$App.make(match$7[0], /* array */[])) : ReasonReact.element(undefined, undefined, String$App.make("Email", /* array */[]));
                              } else {
                                tmp$3 = ReasonReact.element(undefined, undefined, String$App.make("Email", /* array */[]));
                              }
                              var match$8 = Curry._1(form[/* result */2], /* Password */3);
                              var tmp$4;
                              if (match$8 !== undefined) {
                                var match$9 = match$8;
                                tmp$4 = match$9.tag ? true : false;
                              } else {
                                tmp$4 = false;
                              }
                              var match$10 = Curry._1(form[/* result */2], /* Password */3);
                              var tmp$5;
                              if (match$10 !== undefined) {
                                var match$11 = match$10;
                                tmp$5 = match$11.tag ? ReasonReact.element(undefined, undefined, String$App.make(match$11[0], /* array */[])) : ReasonReact.element(undefined, undefined, String$App.make("Password", /* array */[]));
                              } else {
                                tmp$5 = ReasonReact.element(undefined, undefined, String$App.make("Password", /* array */[]));
                              }
                              var match$12 = Curry._1(form[/* result */2], /* PasswordConfirmation */4);
                              var tmp$6;
                              if (match$12 !== undefined) {
                                var match$13 = match$12;
                                tmp$6 = match$13.tag ? true : false;
                              } else {
                                tmp$6 = false;
                              }
                              var match$14 = Curry._1(form[/* result */2], /* PasswordConfirmation */4);
                              var tmp$7;
                              if (match$14 !== undefined) {
                                var match$15 = match$14;
                                tmp$7 = match$15.tag ? ReasonReact.element(undefined, undefined, String$App.make(match$15[0], /* array */[])) : ReasonReact.element(undefined, undefined, String$App.make("Password Confirmation", /* array */[]));
                              } else {
                                tmp$7 = ReasonReact.element(undefined, undefined, String$App.make("Password Confirmation", /* array */[]));
                              }
                              return React.createElement("form", {
                                          onSubmit: (function (param) {
                                              return partial_arg$1(partial_arg, param);
                                            })
                                        }, ReasonReact.element(undefined, undefined, MaterialUi_FormGroup.make(undefined, undefined, undefined, undefined, /* array */[
                                                  ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, undefined, undefined, form[/* submitting */5], tmp, undefined, undefined, undefined, "firstName", undefined, undefined, undefined, undefined, Caml_option.some(tmp$1), /* Normal */-453122489, undefined, undefined, (function (param) {
                                                                        return Curry._1(form[/* blur */7], /* FirstName */0);
                                                                      }), (function ($$event) {
                                                                        return Curry._2(form[/* change */6], /* FirstName */0, update$1(form[/* state */0], $$event.target.value));
                                                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `String */[
                                                                      -976970511,
                                                                      form[/* state */0][/* firstName */1]
                                                                    ], undefined, undefined, /* array */[]))])),
                                                  ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, undefined, undefined, form[/* submitting */5], undefined, undefined, undefined, undefined, "lastName", undefined, undefined, undefined, undefined, Caml_option.some(ReasonReact.element(undefined, undefined, String$App.make("LastName", /* array */[]))), /* Normal */-453122489, undefined, undefined, (function (param) {
                                                                        return Curry._1(form[/* blur */7], /* LastName */1);
                                                                      }), (function ($$event) {
                                                                        return Curry._2(form[/* change */6], /* LastName */1, update$2(form[/* state */0], $$event.target.value));
                                                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `String */[
                                                                      -976970511,
                                                                      form[/* state */0][/* lastName */2]
                                                                    ], undefined, undefined, /* array */[]))])),
                                                  ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, undefined, undefined, form[/* submitting */5], tmp$2, undefined, undefined, undefined, "email", undefined, undefined, undefined, undefined, Caml_option.some(tmp$3), /* Normal */-453122489, undefined, undefined, (function (param) {
                                                                        return Curry._1(form[/* blur */7], /* Email */2);
                                                                      }), (function ($$event) {
                                                                        return Curry._2(form[/* change */6], /* Email */2, update(form[/* state */0], $$event.target.value));
                                                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `String */[
                                                                      -976970511,
                                                                      form[/* state */0][/* email */0]
                                                                    ], undefined, undefined, /* array */[]))])),
                                                  ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, undefined, undefined, form[/* submitting */5], tmp$4, undefined, undefined, undefined, "password", undefined, undefined, undefined, undefined, Caml_option.some(tmp$5), /* Normal */-453122489, undefined, undefined, (function (param) {
                                                                        return Curry._1(form[/* blur */7], /* Password */3);
                                                                      }), (function ($$event) {
                                                                        return Curry._2(form[/* change */6], /* Password */3, update$3(form[/* state */0], $$event.target.value));
                                                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, "password", /* `String */[
                                                                      -976970511,
                                                                      form[/* state */0][/* password */3]
                                                                    ], undefined, undefined, /* array */[]))])),
                                                  ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, undefined, undefined, form[/* submitting */5], tmp$6, undefined, undefined, undefined, "passwordConfirmation", undefined, undefined, undefined, undefined, Caml_option.some(tmp$7), /* Normal */-453122489, undefined, undefined, (function (param) {
                                                                        return Curry._1(form[/* blur */7], /* PasswordConfirmation */4);
                                                                      }), (function ($$event) {
                                                                        return Curry._2(form[/* change */6], /* PasswordConfirmation */4, update$4(form[/* state */0], $$event.target.value));
                                                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, "password", /* `String */[
                                                                      -976970511,
                                                                      form[/* state */0][/* passwordConfirmation */4]
                                                                    ], undefined, undefined, /* array */[]))])),
                                                  ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, /* Dense */-363472001, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, form[/* submitting */5], undefined, undefined, undefined, undefined, undefined, undefined, undefined, "submit", /* Contained */-515484397, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, String$App.make("Submit", /* array */[]))]))])),
                                                  ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, undefined, undefined, undefined, undefined, /* Dense */-363472001, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "/login", undefined, undefined, undefined, /* Outlined */-28821822, undefined, undefined, undefined, undefined, undefined, undefined, (function ($$event) {
                                                                        $$event.preventDefault();
                                                                        return ReasonReact.Router[/* push */0](Config$App.routes[/* login */2]);
                                                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, String$App.make("Back", /* array */[]))]))]))
                                                ])));
                            })))]));
}

var component = ReasonReact.statelessComponent("Register-App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, Header$App.make(/* array */[])), renderBody(/* () */0), ReasonReact.element(undefined, undefined, Footer$App.make(/* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Form = Form;
exports.Styles = Styles;
exports.initialState = initialState;
exports.AsyncFormContainer = AsyncFormContainer;
exports.renderBody = renderBody;
exports.component = component;
exports.make = make;
/* controls Not a pure module */
