// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var uppercased = Css.style(/* :: */[
      Css.textTransform(Css.uppercase),
      /* [] */0
    ]);

var Styles = /* module */[/* uppercased */uppercased];

var component = ReasonReact.statelessComponent("Title-App");

function make($staropt$star, content, _children) {
  var level = $staropt$star !== undefined ? $staropt$star : 1;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              switch (level) {
                case 1 : 
                    return React.createElement("h1", {
                                className: uppercased
                              }, content);
                case 2 : 
                    return React.createElement("h2", undefined, content);
                case 3 : 
                    return React.createElement("h3", undefined, content);
                case 4 : 
                    return React.createElement("h4", undefined, content);
                case 5 : 
                    return React.createElement("h5", undefined, content);
                default:
                  return React.createElement("p", undefined, content);
              }
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* uppercased Not a pure module */
