// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Home$App = require("./pages/Home.bs.js");
var Login$App = require("./pages/Login.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Waiting$App = require("./pages/Waiting.bs.js");
var Register$App = require("./pages/Register.bs.js");

function mapUrlToPage(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "auth" : 
          if (match[1]) {
            return /* Login */1;
          } else {
            return /* Waiting */2;
          }
      case "home" : 
          if (match[1]) {
            return /* Login */1;
          } else {
            return /* Home */0;
          }
      case "login" : 
          return /* Login */1;
      case "register" : 
          if (match[1]) {
            return /* Login */1;
          } else {
            return /* Register */3;
          }
      default:
        return /* Login */1;
    }
  } else {
    return /* Login */1;
  }
}

var component = ReasonReact.reducerComponent("App-App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var warcherId = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(self[/* send */3], /* ChangePage */[mapUrlToPage(url)]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            return ReasonReact.Router[/* unwatchUrl */2](warcherId);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* page */0];
              switch (match) {
                case 0 : 
                    return ReasonReact.element(undefined, undefined, Home$App.make(/* array */[]));
                case 1 : 
                    return ReasonReact.element(undefined, undefined, Login$App.make(/* array */[]));
                case 2 : 
                    return ReasonReact.element(undefined, undefined, Waiting$App.make(/* array */[]));
                case 3 : 
                    return ReasonReact.element(undefined, undefined, Register$App.make(/* array */[]));
                
              }
            }),
          /* initialState */(function (param) {
              return /* record */[/* page */mapUrlToPage(ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0))];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[/* page */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.mapUrlToPage = mapUrlToPage;
exports.component = component;
exports.make = make;
/* component Not a pure module */
