// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Home$SoundpshereApp = require("./Home.bs.js");
var Login$SoundpshereApp = require("./Login.bs.js");
var Register$SoundpshereApp = require("./Register.bs.js");

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "home" : 
          return /* Home */0;
      case "login" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* Login */1;
          }
      case "register" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* Register */2;
          }
      default:
        return /* Home */0;
    }
  } else {
    return /* Home */0;
  }
}

var component = ReasonReact.reducerComponent("App-SoundpshereApp");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var warcherId = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(self[/* send */3], /* ChangeRoute */[mapUrlToRoute(url)]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            return ReasonReact.Router[/* unwatchUrl */2](warcherId);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              var tmp;
              switch (match[/* route */0]) {
                case 0 : 
                    tmp = ReasonReact.element(undefined, undefined, Home$SoundpshereApp.make(/* array */[]));
                    break;
                case 1 : 
                    tmp = ReasonReact.element(undefined, undefined, Login$SoundpshereApp.make(/* array */[]));
                    break;
                case 2 : 
                    tmp = ReasonReact.element(undefined, undefined, Register$SoundpshereApp.make(/* array */[]));
                    break;
                
              }
              return React.createElement("div", undefined, tmp);
            }),
          /* initialState */(function (param) {
              return /* record */[/* route */mapUrlToRoute(ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0))];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.mapUrlToRoute = mapUrlToRoute;
exports.component = component;
exports.make = make;
/* component Not a pure module */
