// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';


var routes = /* record */[
  /* auth */"/auth",
  /* home */"/home",
  /* login */"/login",
  /* register */"/register"
];

exports.routes = routes;
/* No side effect */
