// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var email_000 = /* exec */new RegExp("^[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}$");

var email = /* record */[
  email_000,
  /* error */"Email is incorrect, try again"
];

var password_000 = /* exec */new RegExp("^.{6,}$");

var password = /* record */[
  password_000,
  /* error */"Password length should be more 5 characters"
];

var Rule = /* module */[
  /* email */email,
  /* password */password
];

function test(rule, value) {
  return rule[/* exec */0].test(value);
}

function use(name, value) {
  if (name) {
    var match = password_000.test(value);
    if (match) {
      return /* Ok */Block.__(0, [/* Valid */0]);
    } else {
      return /* Error */Block.__(1, ["Password length should be more 5 characters"]);
    }
  } else {
    var match$1 = email_000.test(value);
    if (match$1) {
      return /* Ok */Block.__(0, [/* Valid */0]);
    } else {
      return /* Error */Block.__(1, ["Email is incorrect, try again"]);
    }
  }
}

var FInterop = /* module */[/* use */use];

exports.Rule = Rule;
exports.test = test;
exports.FInterop = FInterop;
/* email Not a pure module */
